vim.cmd("highlight clear")
vim.g.colors_name = "system"

local function hl(group, opts)
	vim.api.nvim_set_hl(0, group, opts)
end

local c = {
	bg = "NONE",
	black = 0,
	red = 1,
	green = 2,
	yellow = 3,
	blue = 4,
	magenta = 5,
	cyan = 6,
	white = 7,
	bright_black = 8,
	bright_red = 9,
	bright_green = 10,
	bright_yellow = 11,
	bright_blue = 12,
	bright_magenta = 13,
	bright_cyan = 14,
	bright_white = 15,
}

local groups = {
	{ "Normal", { ctermfg = c.white, ctermbg = c.bg } },
	{ "NormalNC", { ctermfg = c.white, ctermbg = c.bg } },
	{ "NormalFloat", { ctermfg = c.white, ctermbg = c.black } },
	{ "FloatBorder", { ctermfg = c.bright_black, ctermbg = c.black } },
	-- Avoid palette collisions (e.g. Comment fg uses bright_black). Use a subtle
	-- background for CursorLine that stays distinct from comment-gray.
	{ "CursorLine", { ctermbg = c.black } },
	{ "CursorLineNr", { ctermfg = c.cyan, cterm = { bold = true } } },
	{ "LineNr", { ctermfg = c.bright_black } },
	{ "SignColumn", { ctermfg = c.bright_black, ctermbg = c.bg } },
	{ "VertSplit", { ctermfg = c.bright_black } },
	{ "WinSeparator", { ctermfg = c.bright_black } },
	{ "StatusLine", { ctermfg = c.white, ctermbg = c.black } },
	{ "StatusLineNC", { ctermfg = c.bright_black, ctermbg = c.black } },
	{ "Visual", { cterm = { reverse = true } } },
	{ "VisualNOS", { cterm = { reverse = true } } },
	{ "Search", { ctermfg = c.black, ctermbg = c.yellow } },
	{ "IncSearch", { ctermfg = c.black, ctermbg = c.cyan } },
	{ "CurSearch", { ctermfg = c.black, ctermbg = c.cyan } },
	{ "Pmenu", { ctermfg = c.white, ctermbg = c.black } },
	{ "PmenuSel", { ctermfg = c.black, ctermbg = c.cyan } },
	{ "PmenuSbar", { ctermbg = c.bright_black } },
	{ "PmenuThumb", { ctermbg = c.white } },
	{ "TabLine", { ctermfg = c.bright_black, ctermbg = c.black } },
	{ "TabLineFill", { ctermbg = c.black } },
	{ "TabLineSel", { ctermfg = c.cyan, ctermbg = c.bg, cterm = { bold = true } } },
	{ "MatchParen", { ctermfg = c.black, ctermbg = c.cyan, cterm = { bold = true } } },
	{ "Cursor", { ctermfg = c.black, ctermbg = c.cyan } },
	{ "CursorIM", { ctermfg = c.black, ctermbg = c.cyan } },

	{ "Comment", { ctermfg = c.bright_black, cterm = { italic = true } } },
	{ "String", { ctermfg = c.green } },
	{ "Character", { ctermfg = c.green } },
	{ "Keyword", { ctermfg = c.magenta } },
	{ "Function", { ctermfg = c.blue } },
	{ "Type", { ctermfg = c.yellow } },
	{ "Constant", { ctermfg = c.cyan } },
	{ "Identifier", { ctermfg = c.white } },
	{ "Statement", { ctermfg = c.magenta } },
	{ "PreProc", { ctermfg = c.cyan } },
	{ "Special", { ctermfg = c.cyan } },
	{ "Error", { ctermfg = c.red } },
	{ "WarningMsg", { ctermfg = c.yellow } },
	{ "Todo", { ctermfg = c.cyan, cterm = { bold = true } } },
	{ "Number", { ctermfg = c.bright_magenta } },
	{ "Boolean", { ctermfg = c.bright_magenta } },
	{ "Float", { ctermfg = c.bright_magenta } },
	{ "Operator", { ctermfg = c.white } },
	{ "Delimiter", { ctermfg = c.white } },
	{ "Title", { ctermfg = c.cyan, cterm = { bold = true } } },

	{ "DiffAdd", { ctermfg = c.green, ctermbg = c.bg } },
	{ "DiffChange", { ctermfg = c.yellow, ctermbg = c.bg } },
	{ "DiffDelete", { ctermfg = c.red, ctermbg = c.bg } },
	{ "DiffText", { ctermfg = c.blue, ctermbg = c.bg } },
	{ "Added", { ctermfg = c.green } },
	{ "Changed", { ctermfg = c.yellow } },
	{ "Removed", { ctermfg = c.red } },

	{ "GitSignsAdd", { ctermfg = c.green } },
	{ "GitSignsChange", { ctermfg = c.yellow } },
	{ "GitSignsDelete", { ctermfg = c.red } },

	{ "NvimTreeNormal", { ctermfg = c.white, ctermbg = c.bg } },
	{ "NvimTreeFolderIcon", { ctermfg = c.cyan } },
	{ "NvimTreeFolderName", { ctermfg = c.cyan } },
	{ "NvimTreeOpenedFolderName", { ctermfg = c.cyan, cterm = { bold = true } } },
	{ "NvimTreeIndentMarker", { ctermfg = c.bright_black } },
	{ "NvimTreeGitDirty", { ctermfg = c.bright_red } },
	{ "NvimTreeGitStaged", { ctermfg = c.green } },
	{ "NvimTreeGitNew", { ctermfg = c.bright_green } },
	{ "NvimTreeGitDeleted", { ctermfg = c.bright_red } },
	{ "NvimTreeGitMerge", { ctermfg = c.bright_magenta } },
	{ "NvimTreeGitRenamed", { ctermfg = c.bright_blue } },

	{ "NeoTreeNormal", { ctermfg = c.white, ctermbg = c.bg } },
	{ "NeoTreeNormalNC", { ctermfg = c.white, ctermbg = c.bg } },
	{ "NeoTreeDirectoryIcon", { ctermfg = c.cyan } },
	{ "NeoTreeDirectoryName", { ctermfg = c.cyan } },
	{ "NeoTreeFileName", { ctermfg = c.white } },
	{ "NeoTreeGitModified", { ctermfg = c.bright_red } },
	{ "NeoTreeGitAdded", { ctermfg = c.bright_green } },
	{ "NeoTreeGitDeleted", { ctermfg = c.bright_red } },
	{ "NeoTreeGitUntracked", { ctermfg = c.bright_red } },
	{ "NeoTreeIndentMarker", { ctermfg = c.bright_black } },

	{ "TelescopeNormal", { ctermfg = c.white, ctermbg = c.bg } },
	{ "TelescopeBorder", { ctermfg = c.bright_black, ctermbg = c.bg } },
	{ "TelescopeSelection", { ctermfg = c.cyan, ctermbg = c.black, cterm = { bold = true } } },
	{ "TelescopePromptPrefix", { ctermfg = c.cyan } },
	{ "TelescopeMatching", { ctermfg = c.yellow, cterm = { bold = true } } },

	{ "DiagnosticError", { ctermfg = c.red } },
	{ "DiagnosticWarn", { ctermfg = c.yellow } },
	{ "DiagnosticInfo", { ctermfg = c.blue } },
	{ "DiagnosticHint", { ctermfg = c.cyan } },

	{ "LspReferenceText", { ctermbg = c.bright_black } },
	{ "LspReferenceRead", { ctermbg = c.bright_black } },
	{ "LspReferenceWrite", { ctermbg = c.bright_black } },

	{ "@variable", { ctermfg = c.white } },
	{ "@variable.builtin", { ctermfg = c.red } },
	{ "@variable.parameter", { ctermfg = c.white } },
	{ "@constant", { ctermfg = c.cyan } },
	{ "@constant.builtin", { ctermfg = c.cyan } },
	{ "@function", { ctermfg = c.blue } },
	{ "@function.builtin", { ctermfg = c.blue } },
	{ "@function.macro", { ctermfg = c.cyan } },
	{ "@keyword", { ctermfg = c.magenta } },
	{ "@keyword.function", { ctermfg = c.magenta } },
	{ "@keyword.return", { ctermfg = c.magenta } },
	{ "@keyword.operator", { ctermfg = c.magenta } },
	{ "@string", { ctermfg = c.green } },
	{ "@string.escape", { ctermfg = c.cyan } },
	{ "@type", { ctermfg = c.yellow } },
	{ "@type.builtin", { ctermfg = c.yellow } },
	{ "@property", { ctermfg = c.white } },
	{ "@field", { ctermfg = c.white } },
	{ "@parameter", { ctermfg = c.white } },
	{ "@punctuation", { ctermfg = c.white } },
	{ "@punctuation.bracket", { ctermfg = c.white } },
	{ "@punctuation.delimiter", { ctermfg = c.white } },
	{ "@operator", { ctermfg = c.white } },
	{ "@comment", { ctermfg = c.bright_black, cterm = { italic = true } } },
	{ "@tag", { ctermfg = c.red } },
	{ "@tag.attribute", { ctermfg = c.yellow } },
	{ "@tag.delimiter", { ctermfg = c.white } },
	{ "@lsp.type.property", { ctermfg = c.white } },
	{ "@variable.member", { ctermfg = c.white } },

	{ "lualine_a_normal", { ctermfg = c.black, ctermbg = c.cyan, cterm = { bold = true } } },
	{ "lualine_a_insert", { ctermfg = c.black, ctermbg = c.green, cterm = { bold = true } } },
	{ "lualine_a_visual", { ctermfg = c.black, ctermbg = c.magenta, cterm = { bold = true } } },
	{ "lualine_a_command", { ctermfg = c.black, ctermbg = c.yellow, cterm = { bold = true } } },
	{ "lualine_a_replace", { ctermfg = c.black, ctermbg = c.red, cterm = { bold = true } } },
	{ "lualine_a_inactive", { ctermfg = c.bright_black, ctermbg = c.black } },

	{ "lualine_b_normal", { ctermfg = c.cyan, ctermbg = c.bright_black } },
	{ "lualine_b_insert", { ctermfg = c.cyan, ctermbg = c.bright_black } },
	{ "lualine_b_visual", { ctermfg = c.cyan, ctermbg = c.bright_black } },
	{ "lualine_b_command", { ctermfg = c.cyan, ctermbg = c.bright_black } },
	{ "lualine_b_replace", { ctermfg = c.cyan, ctermbg = c.bright_black } },
	{ "lualine_b_inactive", { ctermfg = c.bright_black, ctermbg = c.black } },

	{ "lualine_c_normal", { ctermfg = c.cyan, ctermbg = c.black } },
	{ "lualine_c_insert", { ctermfg = c.cyan, ctermbg = c.black } },
	{ "lualine_c_visual", { ctermfg = c.cyan, ctermbg = c.black } },
	{ "lualine_c_command", { ctermfg = c.cyan, ctermbg = c.black } },
	{ "lualine_c_replace", { ctermfg = c.cyan, ctermbg = c.black } },
	{ "lualine_c_inactive", { ctermfg = c.bright_black, ctermbg = c.black } },

	{ "lualine_x_normal", { ctermfg = c.cyan, ctermbg = c.black } },
	{ "lualine_x_insert", { ctermfg = c.cyan, ctermbg = c.black } },
	{ "lualine_x_visual", { ctermfg = c.cyan, ctermbg = c.black } },
	{ "lualine_x_command", { ctermfg = c.cyan, ctermbg = c.black } },
	{ "lualine_x_replace", { ctermfg = c.cyan, ctermbg = c.black } },
	{ "lualine_x_inactive", { ctermfg = c.bright_black, ctermbg = c.black } },

	{ "lualine_y_normal", { ctermfg = c.cyan, ctermbg = c.bright_black } },
	{ "lualine_y_insert", { ctermfg = c.cyan, ctermbg = c.bright_black } },
	{ "lualine_y_visual", { ctermfg = c.cyan, ctermbg = c.bright_black } },
	{ "lualine_y_command", { ctermfg = c.cyan, ctermbg = c.bright_black } },
	{ "lualine_y_replace", { ctermfg = c.cyan, ctermbg = c.bright_black } },
	{ "lualine_y_inactive", { ctermfg = c.bright_black, ctermbg = c.black } },

	{ "lualine_z_normal", { ctermfg = c.black, ctermbg = c.cyan, cterm = { bold = true } } },
	{ "lualine_z_insert", { ctermfg = c.black, ctermbg = c.green, cterm = { bold = true } } },
	{ "lualine_z_visual", { ctermfg = c.black, ctermbg = c.magenta, cterm = { bold = true } } },
	{ "lualine_z_command", { ctermfg = c.black, ctermbg = c.yellow, cterm = { bold = true } } },
	{ "lualine_z_replace", { ctermfg = c.black, ctermbg = c.red, cterm = { bold = true } } },
	{ "lualine_z_inactive", { ctermfg = c.bright_black, ctermbg = c.black } },
}

for _, group in ipairs(groups) do
	hl(group[1], group[2])
end

vim.api.nvim_create_autocmd("ColorScheme", {
	pattern = "system",
	callback = function()
		for _, group in ipairs(groups) do
			hl(group[1], group[2])
		end
	end,
})

return true
