theme: 
  dark: poimandres-terminal
  light: poimandres-terminal
lastChangelogVersion: 13.16.4
modelRoles: 
  default: fireworks/accounts/fireworks/routers/kimi-k2p5-turbo
  vision: cliproxy/gpt-5.4:high
  smol: fireworks/accounts/fireworks/routers/kimi-k2p5-turbo
  slow: cliproxy/gpt-5.4:xhigh
  plan: cliproxy/gpt-5.4:xhigh
task: 
  agentModelOverrides: 
    {}
  disabledAgents: 
    []
disabledExtensions: 
  []
statusLine: 
  preset: default
  separator: pipe
display: 
  showTokenUsage: true