theme: 
  dark: poimandres-terminal
  light: poimandres-terminal
lastChangelogVersion: 13.15.3
modelRoles: 
  default: cliproxy/gpt-5.4:high
  vision: openrouter/openrouter/healer-alpha:high
  smol: opencode-go/minimax-m2.5
  slow: cliproxy/gpt-5.4:xhigh
  plan: cliproxy/gpt-5.4:xhigh
task: 
  agentModelOverrides: 
    {}
  disabledAgents: 
    []
disabledExtensions: 
  []
statusLine: 
  preset: default
  separator: pipe
display: 
  showTokenUsage: true