theme: 
  dark: poimandres-terminal
  light: poimandres-terminal
lastChangelogVersion: 15.1.3
modelRoles: 
  default: openai-codex/gpt-5.5:medium
  vision: kimi-code/kimi-for-coding:high
  smol: openai-codex/gpt-5.4-nano:low
  slow: openai-codex/gpt-5.4:xhigh
  plan: openai-codex/gpt-5.4:xhigh
  commit: kimi-code/kimi-for-coding:high
  designer: kimi-code/kimi-for-coding:high
task: 
  agentModelOverrides: 
    {}
  disabledAgents: 
    []
disabledExtensions: 
  []
statusLine: 
  preset: default
  separator: pipe
display: 
  showTokenUsage: true